[package]
name = "serde_rusoto_dynamodb"
version = "0.1.0"
authors = ["kolektiv <andrew@xyncro.com>"]
edition = "2018"

[dependencies]
itoa = "0.4.3"
maplit = "1.0.1"
rusoto_dynamodb = "0.37.0"
ryu = "0.2.7"
serde = { version = "1.0.89", features = ["derive"] }